spring.application.name=RESTAPIs
spring.config.import=file:env.properties
spring.datasource.driver-class-name= com.mysql.cj.jdbc.Driver
spring.datasource.url = jdbc:mysql://localhost:3306/ecomdb
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.show-sql= true
spring.jpa.hibernate.ddl-auto=update


security.jwt.secret-key=fQzqQS8BDmAnAbJ4Z6Wrn2usveMdkdNcOj08jesY0bgXo47X7YFjUtdU4GjQDjE79DjSztR4oHRUIur81uNEJA==
security.jwt.expiration-time=3600000

project.image=C:/Users/Lenovo/Documents/springboot/RESTAPIs/uploads/products

khalti.secret-key = 3e55c4880d9144b3ab02d0ef64aec3f9
khalti.initiate_url = https://dev.khalti.com/api/v2/epayment/initiate/
khalti.lookup-url = https://dev.khalti.com/api/v2/epayment/lookup/
khalti.return-url = https://localhost:8000/payment/callback
khalti.website-url = http://localhost:8080

debug=true
