spring.application.name=RESTAPIs
spring.config.import=file:env.properties
spring.datasource.driver-class-name= com.mysql.cj.jdbc.Driver
spring.datasource.url = jdbc:mysql://localhost:3306/ecomdb
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.show-sql= true
spring.jpa.hibernate.ddl-auto=update


security.jwt.secret-key=${JWT_SECRET_KEY}
security.jwt.expiration-time=3600000

project.image=C:/Users/Lenovo/Documents/springboot/RESTAPIs/uploads/products

khalti.secret-key = ${KHALTI_SECRET_KEY}
khalti.initiate_url = https://dev.khalti.com/api/v2/epayment/initiate/
khalti.lookup-url = https://dev.khalti.com/api/v2/epayment/lookup/
khalti.return-url = https://localhost:8000/payment/callback
khalti.website-url = http://localhost:8080

debug=true



spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.redirect-uri=https://localhost:8080/grantcode
spring.security.oauth2.client.registration.google.client-name=Google
spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://openidconnect.googleapis.com/v1/userinfo


# PRODUCER (Sending the event)
spring.kafka.producer.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# CONSUMER (Receiving the event)
spring.kafka.consumer.bootstrap-servers=localhost:9092
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# IMPORTANT: Allow Spring to trust the package where your Event class lives
spring.kafka.consumer.properties.spring.json.trusted.packages=com.example.restapis.dto,com.example.event
# Use the ErrorHandlingDeserializer to catch "Poison Pills"
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer

# Tell it which class to turn the JSON into
spring.kafka.properties.spring.json.trusted.packages=com.example.event